import React from 'react'
import './tailwind.css'
import NavigationBar from '@/components/NavigationBar/NavigationBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='bg-slate-900 py-4 px-[3rem] flex justify-between text-white'>
          <div className='bg-red-700 inline-block'>LOGO</div>
          <div className='bg-red-700 inline-block'>LOGO</div>
        </div>
        {children}
        </body>
    </html>
  )
}
